image: node:18

stages:
  - install
  - test
  - build

before_script:
  - cd Full-Stack

cache:
  paths:
    - Full-Stack/node_modules/

install_dependencies:
  stage: install
  script:
    - npm install

test_app:
  stage: test
  script:
    - npm test
  allow_failure: true   # OK if you don't have tests yet

build_app:
  stage: build
  script:
    - npm run build || echo "No build step defined"
