image: node:18

stages:
  - build
  - test
  - deploy

before_script:
  - cd Full-Stack

cache:
  paths:
    - Full-Stack/node_modules/

# -------- BUILD --------
build_app:
  stage: build
  script:
    - echo "BUILD:Installing dependencies"
    - npm install

# -------- TEST --------
test_app:
  stage: test
  script:
    - echo "TEST:No automated tests yet, skipping test execution"

# -------- DEPLOY --------
deploy_app:
  stage: deploy
  script:
    - echo "DEPLOY:Application is ready for deployment"
